package com.stepandemianenko.dsaprep.domain.model

object Neetcode150Catalog {
    val problems: List<KnownProblem> = listOf(
        p("Contains Duplicate", "contains-duplicate/", ProblemDifficulty.EASY, ProblemTopic.HASHMAP, "Arrays & Hashing"),
        p("Valid Anagram", "valid-anagram/", ProblemDifficulty.EASY, ProblemTopic.HASHMAP, "Arrays & Hashing"),
        p("Two Sum", "two-sum/", ProblemDifficulty.EASY, ProblemTopic.HASHMAP, "Arrays & Hashing"),
        p("Group Anagrams", "group-anagrams/", ProblemDifficulty.MEDIUM, ProblemTopic.HASHMAP, "Arrays & Hashing"),
        p("Top K Frequent Elements", "top-k-frequent-elements/", ProblemDifficulty.MEDIUM, ProblemTopic.HASHMAP, "Arrays & Hashing"),
        p("Encode and Decode Strings", "encode-and-decode-strings/", ProblemDifficulty.MEDIUM, ProblemTopic.ARRAY, "Arrays & Hashing"),
        p("Product of Array Except Self", "product-of-array-except-self/", ProblemDifficulty.MEDIUM, ProblemTopic.ARRAY, "Arrays & Hashing"),
        p("Valid Sudoku", "valid-sudoku/", ProblemDifficulty.MEDIUM, ProblemTopic.HASHMAP, "Arrays & Hashing"),
        p("Longest Consecutive Sequence", "longest-consecutive-sequence/", ProblemDifficulty.MEDIUM, ProblemTopic.HASHMAP, "Arrays & Hashing"),
        p("Valid Palindrome", "valid-palindrome/", ProblemDifficulty.EASY, ProblemTopic.TWO_POINTERS, "Two Pointers"),
        p("Two Sum II Input Array Is Sorted", "two-sum-ii-input-array-is-sorted/", ProblemDifficulty.MEDIUM, ProblemTopic.TWO_POINTERS, "Two Pointers"),
        p("3Sum", "3sum/", ProblemDifficulty.MEDIUM, ProblemTopic.TWO_POINTERS, "Two Pointers"),
        p("Container With Most Water", "container-with-most-water/", ProblemDifficulty.MEDIUM, ProblemTopic.TWO_POINTERS, "Two Pointers"),
        p("Trapping Rain Water", "trapping-rain-water/", ProblemDifficulty.HARD, ProblemTopic.TWO_POINTERS, "Two Pointers"),
        p("Best Time to Buy And Sell Stock", "best-time-to-buy-and-sell-stock/", ProblemDifficulty.EASY, ProblemTopic.SLIDING_WINDOW, "Sliding Window"),
        p("Longest Substring Without Repeating Characters", "longest-substring-without-repeating-characters/", ProblemDifficulty.MEDIUM, ProblemTopic.SLIDING_WINDOW, "Sliding Window"),
        p("Longest Repeating Character Replacement", "longest-repeating-character-replacement/", ProblemDifficulty.MEDIUM, ProblemTopic.SLIDING_WINDOW, "Sliding Window"),
        p("Permutation In String", "permutation-in-string/", ProblemDifficulty.MEDIUM, ProblemTopic.SLIDING_WINDOW, "Sliding Window"),
        p("Minimum Window Substring", "minimum-window-substring/", ProblemDifficulty.HARD, ProblemTopic.SLIDING_WINDOW, "Sliding Window"),
        p("Sliding Window Maximum", "sliding-window-maximum/", ProblemDifficulty.HARD, ProblemTopic.SLIDING_WINDOW, "Sliding Window"),
        p("Valid Parentheses", "valid-parentheses/", ProblemDifficulty.EASY, ProblemTopic.STACK, "Stack"),
        p("Min Stack", "min-stack/", ProblemDifficulty.MEDIUM, ProblemTopic.STACK, "Stack"),
        p("Evaluate Reverse Polish Notation", "evaluate-reverse-polish-notation/", ProblemDifficulty.MEDIUM, ProblemTopic.STACK, "Stack"),
        p("Daily Temperatures", "daily-temperatures/", ProblemDifficulty.MEDIUM, ProblemTopic.STACK, "Stack"),
        p("Car Fleet", "car-fleet/", ProblemDifficulty.MEDIUM, ProblemTopic.STACK, "Stack"),
        p("Largest Rectangle In Histogram", "largest-rectangle-in-histogram/", ProblemDifficulty.HARD, ProblemTopic.STACK, "Stack"),
        p("Binary Search", "binary-search/", ProblemDifficulty.EASY, ProblemTopic.BINARY_SEARCH, "Binary Search"),
        p("Search a 2D Matrix", "search-a-2d-matrix/", ProblemDifficulty.MEDIUM, ProblemTopic.BINARY_SEARCH, "Binary Search"),
        p("Koko Eating Bananas", "koko-eating-bananas/", ProblemDifficulty.MEDIUM, ProblemTopic.BINARY_SEARCH, "Binary Search"),
        p("Find Minimum In Rotated Sorted Array", "find-minimum-in-rotated-sorted-array/", ProblemDifficulty.MEDIUM, ProblemTopic.BINARY_SEARCH, "Binary Search"),
        p("Search In Rotated Sorted Array", "search-in-rotated-sorted-array/", ProblemDifficulty.MEDIUM, ProblemTopic.BINARY_SEARCH, "Binary Search"),
        p("Time Based Key Value Store", "time-based-key-value-store/", ProblemDifficulty.MEDIUM, ProblemTopic.BINARY_SEARCH, "Binary Search"),
        p("Median of Two Sorted Arrays", "median-of-two-sorted-arrays/", ProblemDifficulty.HARD, ProblemTopic.BINARY_SEARCH, "Binary Search"),
        p("Reverse Linked List", "reverse-linked-list/", ProblemDifficulty.EASY, ProblemTopic.LINKED_LIST, "Linked List"),
        p("Merge Two Sorted Lists", "merge-two-sorted-lists/", ProblemDifficulty.EASY, ProblemTopic.LINKED_LIST, "Linked List"),
        p("Linked List Cycle", "linked-list-cycle/", ProblemDifficulty.EASY, ProblemTopic.LINKED_LIST, "Linked List"),
        p("Reorder List", "reorder-list/", ProblemDifficulty.MEDIUM, ProblemTopic.LINKED_LIST, "Linked List"),
        p("Remove Nth Node From End of List", "remove-nth-node-from-end-of-list/", ProblemDifficulty.MEDIUM, ProblemTopic.LINKED_LIST, "Linked List"),
        p("Copy List With Random Pointer", "copy-list-with-random-pointer/", ProblemDifficulty.MEDIUM, ProblemTopic.LINKED_LIST, "Linked List"),
        p("Add Two Numbers", "add-two-numbers/", ProblemDifficulty.MEDIUM, ProblemTopic.LINKED_LIST, "Linked List"),
        p("Find The Duplicate Number", "find-the-duplicate-number/", ProblemDifficulty.MEDIUM, ProblemTopic.LINKED_LIST, "Linked List"),
        p("LRU Cache", "lru-cache/", ProblemDifficulty.MEDIUM, ProblemTopic.LINKED_LIST, "Linked List"),
        p("Merge K Sorted Lists", "merge-k-sorted-lists/", ProblemDifficulty.HARD, ProblemTopic.LINKED_LIST, "Linked List"),
        p("Reverse Nodes In K Group", "reverse-nodes-in-k-group/", ProblemDifficulty.HARD, ProblemTopic.LINKED_LIST, "Linked List"),
        p("Invert Binary Tree", "invert-binary-tree/", ProblemDifficulty.EASY, ProblemTopic.TREE, "Trees"),
        p("Maximum Depth of Binary Tree", "maximum-depth-of-binary-tree/", ProblemDifficulty.EASY, ProblemTopic.TREE, "Trees"),
        p("Diameter of Binary Tree", "diameter-of-binary-tree/", ProblemDifficulty.EASY, ProblemTopic.TREE, "Trees"),
        p("Balanced Binary Tree", "balanced-binary-tree/", ProblemDifficulty.EASY, ProblemTopic.TREE, "Trees"),
        p("Same Tree", "same-tree/", ProblemDifficulty.EASY, ProblemTopic.TREE, "Trees"),
        p("Subtree of Another Tree", "subtree-of-another-tree/", ProblemDifficulty.EASY, ProblemTopic.TREE, "Trees"),
        p("Lowest Common Ancestor of a Binary Search Tree", "lowest-common-ancestor-of-a-binary-search-tree/", ProblemDifficulty.MEDIUM, ProblemTopic.TREE, "Trees"),
        p("Binary Tree Level Order Traversal", "binary-tree-level-order-traversal/", ProblemDifficulty.MEDIUM, ProblemTopic.TREE, "Trees"),
        p("Binary Tree Right Side View", "binary-tree-right-side-view/", ProblemDifficulty.MEDIUM, ProblemTopic.TREE, "Trees"),
        p("Count Good Nodes In Binary Tree", "count-good-nodes-in-binary-tree/", ProblemDifficulty.MEDIUM, ProblemTopic.TREE, "Trees"),
        p("Validate Binary Search Tree", "validate-binary-search-tree/", ProblemDifficulty.MEDIUM, ProblemTopic.TREE, "Trees"),
        p("Kth Smallest Element In a Bst", "kth-smallest-element-in-a-bst/", ProblemDifficulty.MEDIUM, ProblemTopic.TREE, "Trees"),
        p("Construct Binary Tree From Preorder And Inorder Traversal", "construct-binary-tree-from-preorder-and-inorder-traversal/", ProblemDifficulty.MEDIUM, ProblemTopic.TREE, "Trees"),
        p("Binary Tree Maximum Path Sum", "binary-tree-maximum-path-sum/", ProblemDifficulty.HARD, ProblemTopic.TREE, "Trees"),
        p("Serialize And Deserialize Binary Tree", "serialize-and-deserialize-binary-tree/", ProblemDifficulty.HARD, ProblemTopic.TREE, "Trees"),
        p("Kth Largest Element In a Stream", "kth-largest-element-in-a-stream/", ProblemDifficulty.EASY, ProblemTopic.HEAP, "Heap / Priority Queue"),
        p("Last Stone Weight", "last-stone-weight/", ProblemDifficulty.EASY, ProblemTopic.HEAP, "Heap / Priority Queue"),
        p("K Closest Points to Origin", "k-closest-points-to-origin/", ProblemDifficulty.MEDIUM, ProblemTopic.HEAP, "Heap / Priority Queue"),
        p("Kth Largest Element In An Array", "kth-largest-element-in-an-array/", ProblemDifficulty.MEDIUM, ProblemTopic.HEAP, "Heap / Priority Queue"),
        p("Task Scheduler", "task-scheduler/", ProblemDifficulty.MEDIUM, ProblemTopic.HEAP, "Heap / Priority Queue"),
        p("Design Twitter", "design-twitter/", ProblemDifficulty.MEDIUM, ProblemTopic.HEAP, "Heap / Priority Queue"),
        p("Find Median From Data Stream", "find-median-from-data-stream/", ProblemDifficulty.HARD, ProblemTopic.HEAP, "Heap / Priority Queue"),
        p("Subsets", "subsets/", ProblemDifficulty.MEDIUM, ProblemTopic.BACKTRACKING, "Backtracking"),
        p("Combination Sum", "combination-sum/", ProblemDifficulty.MEDIUM, ProblemTopic.BACKTRACKING, "Backtracking"),
        p("Combination Sum II", "combination-sum-ii/", ProblemDifficulty.MEDIUM, ProblemTopic.BACKTRACKING, "Backtracking"),
        p("Permutations", "permutations/", ProblemDifficulty.MEDIUM, ProblemTopic.BACKTRACKING, "Backtracking"),
        p("Subsets II", "subsets-ii/", ProblemDifficulty.MEDIUM, ProblemTopic.BACKTRACKING, "Backtracking"),
        p("Generate Parentheses", "generate-parentheses/", ProblemDifficulty.MEDIUM, ProblemTopic.BACKTRACKING, "Backtracking"),
        p("Word Search", "word-search/", ProblemDifficulty.MEDIUM, ProblemTopic.BACKTRACKING, "Backtracking"),
        p("Palindrome Partitioning", "palindrome-partitioning/", ProblemDifficulty.MEDIUM, ProblemTopic.BACKTRACKING, "Backtracking"),
        p("Letter Combinations of a Phone Number", "letter-combinations-of-a-phone-number/", ProblemDifficulty.MEDIUM, ProblemTopic.BACKTRACKING, "Backtracking"),
        p("N Queens", "n-queens/", ProblemDifficulty.HARD, ProblemTopic.BACKTRACKING, "Backtracking"),
        p("Implement Trie Prefix Tree", "implement-trie-prefix-tree/", ProblemDifficulty.MEDIUM, ProblemTopic.TRIE, "Tries"),
        p("Design Add And Search Words Data Structure", "design-add-and-search-words-data-structure/", ProblemDifficulty.MEDIUM, ProblemTopic.TRIE, "Tries"),
        p("Word Search II", "word-search-ii/", ProblemDifficulty.HARD, ProblemTopic.TRIE, "Tries"),
        p("Number of Islands", "number-of-islands/", ProblemDifficulty.MEDIUM, ProblemTopic.GRAPH, "Graphs"),
        p("Max Area of Island", "max-area-of-island/", ProblemDifficulty.MEDIUM, ProblemTopic.GRAPH, "Graphs"),
        p("Clone Graph", "clone-graph/", ProblemDifficulty.MEDIUM, ProblemTopic.GRAPH, "Graphs"),
        p("Walls And Gates", "walls-and-gates/", ProblemDifficulty.MEDIUM, ProblemTopic.GRAPH, "Graphs"),
        p("Rotting Oranges", "rotting-oranges/", ProblemDifficulty.MEDIUM, ProblemTopic.GRAPH, "Graphs"),
        p("Pacific Atlantic Water Flow", "pacific-atlantic-water-flow/", ProblemDifficulty.MEDIUM, ProblemTopic.GRAPH, "Graphs"),
        p("Surrounded Regions", "surrounded-regions/", ProblemDifficulty.MEDIUM, ProblemTopic.GRAPH, "Graphs"),
        p("Course Schedule", "course-schedule/", ProblemDifficulty.MEDIUM, ProblemTopic.GRAPH, "Graphs"),
        p("Course Schedule II", "course-schedule-ii/", ProblemDifficulty.MEDIUM, ProblemTopic.GRAPH, "Graphs"),
        p("Graph Valid Tree", "graph-valid-tree/", ProblemDifficulty.MEDIUM, ProblemTopic.GRAPH, "Graphs"),
        p("Number of Connected Components In An Undirected Graph", "number-of-connected-components-in-an-undirected-graph/", ProblemDifficulty.MEDIUM, ProblemTopic.GRAPH, "Graphs"),
        p("Redundant Connection", "redundant-connection/", ProblemDifficulty.MEDIUM, ProblemTopic.GRAPH, "Graphs"),
        p("Word Ladder", "word-ladder/", ProblemDifficulty.HARD, ProblemTopic.GRAPH, "Graphs"),
        p("Network Delay Time", "network-delay-time/", ProblemDifficulty.MEDIUM, ProblemTopic.ADVANCED_GRAPH, "Advanced Graphs"),
        p("Reconstruct Itinerary", "reconstruct-itinerary/", ProblemDifficulty.HARD, ProblemTopic.ADVANCED_GRAPH, "Advanced Graphs"),
        p("Min Cost to Connect All Points", "min-cost-to-connect-all-points/", ProblemDifficulty.MEDIUM, ProblemTopic.ADVANCED_GRAPH, "Advanced Graphs"),
        p("Swim In Rising Water", "swim-in-rising-water/", ProblemDifficulty.HARD, ProblemTopic.ADVANCED_GRAPH, "Advanced Graphs"),
        p("Alien Dictionary", "alien-dictionary/", ProblemDifficulty.HARD, ProblemTopic.ADVANCED_GRAPH, "Advanced Graphs"),
        p("Cheapest Flights Within K Stops", "cheapest-flights-within-k-stops/", ProblemDifficulty.MEDIUM, ProblemTopic.ADVANCED_GRAPH, "Advanced Graphs"),
        p("Climbing Stairs", "climbing-stairs/", ProblemDifficulty.EASY, ProblemTopic.DYNAMIC_PROGRAMMING, "1-D Dynamic Programming"),
        p("Min Cost Climbing Stairs", "min-cost-climbing-stairs/", ProblemDifficulty.EASY, ProblemTopic.DYNAMIC_PROGRAMMING, "1-D Dynamic Programming"),
        p("House Robber", "house-robber/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "1-D Dynamic Programming"),
        p("House Robber II", "house-robber-ii/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "1-D Dynamic Programming"),
        p("Longest Palindromic Substring", "longest-palindromic-substring/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "1-D Dynamic Programming"),
        p("Palindromic Substrings", "palindromic-substrings/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "1-D Dynamic Programming"),
        p("Decode Ways", "decode-ways/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "1-D Dynamic Programming"),
        p("Coin Change", "coin-change/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "1-D Dynamic Programming"),
        p("Maximum Product Subarray", "maximum-product-subarray/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "1-D Dynamic Programming"),
        p("Word Break", "word-break/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "1-D Dynamic Programming"),
        p("Longest Increasing Subsequence", "longest-increasing-subsequence/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "1-D Dynamic Programming"),
        p("Partition Equal Subset Sum", "partition-equal-subset-sum/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "1-D Dynamic Programming"),
        p("Unique Paths", "unique-paths/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "2-D Dynamic Programming"),
        p("Longest Common Subsequence", "longest-common-subsequence/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "2-D Dynamic Programming"),
        p("Best Time to Buy And Sell Stock With Cooldown", "best-time-to-buy-and-sell-stock-with-cooldown/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "2-D Dynamic Programming"),
        p("Coin Change II", "coin-change-ii/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "2-D Dynamic Programming"),
        p("Target Sum", "target-sum/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "2-D Dynamic Programming"),
        p("Interleaving String", "interleaving-string/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "2-D Dynamic Programming"),
        p("Longest Increasing Path In a Matrix", "longest-increasing-path-in-a-matrix/", ProblemDifficulty.HARD, ProblemTopic.DYNAMIC_PROGRAMMING, "2-D Dynamic Programming"),
        p("Distinct Subsequences", "distinct-subsequences/", ProblemDifficulty.HARD, ProblemTopic.DYNAMIC_PROGRAMMING, "2-D Dynamic Programming"),
        p("Edit Distance", "edit-distance/", ProblemDifficulty.MEDIUM, ProblemTopic.DYNAMIC_PROGRAMMING, "2-D Dynamic Programming"),
        p("Burst Balloons", "burst-balloons/", ProblemDifficulty.HARD, ProblemTopic.DYNAMIC_PROGRAMMING, "2-D Dynamic Programming"),
        p("Regular Expression Matching", "regular-expression-matching/", ProblemDifficulty.HARD, ProblemTopic.DYNAMIC_PROGRAMMING, "2-D Dynamic Programming"),
        p("Maximum Subarray", "maximum-subarray/", ProblemDifficulty.MEDIUM, ProblemTopic.GREEDY, "Greedy"),
        p("Jump Game", "jump-game/", ProblemDifficulty.MEDIUM, ProblemTopic.GREEDY, "Greedy"),
        p("Jump Game II", "jump-game-ii/", ProblemDifficulty.MEDIUM, ProblemTopic.GREEDY, "Greedy"),
        p("Gas Station", "gas-station/", ProblemDifficulty.MEDIUM, ProblemTopic.GREEDY, "Greedy"),
        p("Hand of Straights", "hand-of-straights/", ProblemDifficulty.MEDIUM, ProblemTopic.GREEDY, "Greedy"),
        p("Merge Triplets to Form Target Triplet", "merge-triplets-to-form-target-triplet/", ProblemDifficulty.MEDIUM, ProblemTopic.GREEDY, "Greedy"),
        p("Partition Labels", "partition-labels/", ProblemDifficulty.MEDIUM, ProblemTopic.GREEDY, "Greedy"),
        p("Valid Parenthesis String", "valid-parenthesis-string/", ProblemDifficulty.MEDIUM, ProblemTopic.GREEDY, "Greedy"),
        p("Insert Interval", "insert-interval/", ProblemDifficulty.MEDIUM, ProblemTopic.INTERVALS, "Intervals"),
        p("Merge Intervals", "merge-intervals/", ProblemDifficulty.MEDIUM, ProblemTopic.INTERVALS, "Intervals"),
        p("Non Overlapping Intervals", "non-overlapping-intervals/", ProblemDifficulty.MEDIUM, ProblemTopic.INTERVALS, "Intervals"),
        p("Meeting Rooms", "meeting-rooms/", ProblemDifficulty.EASY, ProblemTopic.INTERVALS, "Intervals"),
        p("Meeting Rooms II", "meeting-rooms-ii/", ProblemDifficulty.MEDIUM, ProblemTopic.INTERVALS, "Intervals"),
        p("Minimum Interval to Include Each Query", "minimum-interval-to-include-each-query/", ProblemDifficulty.HARD, ProblemTopic.INTERVALS, "Intervals"),
        p("Rotate Image", "rotate-image/", ProblemDifficulty.MEDIUM, ProblemTopic.MATH_GEOMETRY, "Math & Geometry"),
        p("Spiral Matrix", "spiral-matrix/", ProblemDifficulty.MEDIUM, ProblemTopic.MATH_GEOMETRY, "Math & Geometry"),
        p("Set Matrix Zeroes", "set-matrix-zeroes/", ProblemDifficulty.MEDIUM, ProblemTopic.MATH_GEOMETRY, "Math & Geometry"),
        p("Happy Number", "happy-number/", ProblemDifficulty.EASY, ProblemTopic.MATH_GEOMETRY, "Math & Geometry"),
        p("Plus One", "plus-one/", ProblemDifficulty.EASY, ProblemTopic.MATH_GEOMETRY, "Math & Geometry"),
        p("Pow(x, n)", "powx-n/", ProblemDifficulty.MEDIUM, ProblemTopic.MATH_GEOMETRY, "Math & Geometry"),
        p("Multiply Strings", "multiply-strings/", ProblemDifficulty.MEDIUM, ProblemTopic.MATH_GEOMETRY, "Math & Geometry"),
        p("Detect Squares", "detect-squares/", ProblemDifficulty.MEDIUM, ProblemTopic.MATH_GEOMETRY, "Math & Geometry"),
        p("Single Number", "single-number/", ProblemDifficulty.EASY, ProblemTopic.BIT_MANIPULATION, "Bit Manipulation"),
        p("Number of 1 Bits", "number-of-1-bits/", ProblemDifficulty.EASY, ProblemTopic.BIT_MANIPULATION, "Bit Manipulation"),
        p("Counting Bits", "counting-bits/", ProblemDifficulty.EASY, ProblemTopic.BIT_MANIPULATION, "Bit Manipulation"),
        p("Reverse Bits", "reverse-bits/", ProblemDifficulty.EASY, ProblemTopic.BIT_MANIPULATION, "Bit Manipulation"),
        p("Missing Number", "missing-number/", ProblemDifficulty.EASY, ProblemTopic.BIT_MANIPULATION, "Bit Manipulation"),
        p("Sum of Two Integers", "sum-of-two-integers/", ProblemDifficulty.MEDIUM, ProblemTopic.BIT_MANIPULATION, "Bit Manipulation"),
        p("Reverse Integer", "reverse-integer/", ProblemDifficulty.MEDIUM, ProblemTopic.BIT_MANIPULATION, "Bit Manipulation")
    )

    fun search(query: String, limit: Int = 8): List<KnownProblem> {
        val normalized = query.trim().lowercase()
        if (normalized.isBlank()) return emptyList()
        return problems
            .asSequence()
            .filter {
                it.title.lowercase().contains(normalized) ||
                    it.pattern.lowercase().contains(normalized) ||
                    it.difficulty.name.lowercase().contains(normalized)
            }
            .take(limit)
            .toList()
    }

    private fun p(
        title: String,
        link: String,
        difficulty: ProblemDifficulty,
        topic: ProblemTopic,
        pattern: String
    ): KnownProblem = KnownProblem(
        title = title,
        link = link,
        difficulty = difficulty,
        topic = topic,
        pattern = pattern
    )
}
